version: '3.4'

services:

  db:
    image: mysql
    restart: always
    ports:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - db:db
    ports:
    - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root